image: docker:latest

    #image: docker:latest
services:
  - docker:dind
#
#image: frolvlad/alpine-oraclejdk8
#image: openjdk:8-jdk

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: production

stages:
  - build
  - package
  - deploy

gradle-build:
  image: openjdk:8-jdk
  stage: build
  script: "./gradlew clean build"
  artifacts:
    paths:
      - build/libs/*.jar

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/gdong/dlmonkey .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/gdong/dlmonkey

#deploy_staging:
#  stage: deploy
#  script:
#    - echo "Deploy to staging server"
#    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
#    - docker pull registry.gitlab.com/gdong/dlmonkey
#    - docker run -dp 9876:8080 --name dlmonkey -t registry.gitlab.com/gdong/dlmonkey
#  environment:
#    name: staging
#    url: http://localhost:9876
#  only:
#    - master
#  tags:
#    - staging

deploy_production:
  stage: deploy
  script:
    - echo "Deploying to production server"
    - docker stop dlmonkey || true && docker rm dlmonkey || true
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/gdong/dlmonkey
    - docker run -dp 127.0.0.1:9876:8080 --name dlmonkey -t registry.gitlab.com/gdong/dlmonkey --spring.profiles.active=$SPRING_PROFILES_ACTIVE
  environment:
    name: production
    url: http://www.dlmonkey.com
  when: manual
  only:
    - master
  tags:
    - production
    - docker
