image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - build
  - package
  - deploy

gradle-build:
  image: openjdk:8-jdk
  stage: build
  script: "./gradlew clean build"
  artifacts:
    paths:
      - build/libs/*.jar

docker-build:
  stage: package
  script:
    - docker build -t registry.gitlab.com/gdong/dlmonkey .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/gdong/dlmonkey

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker pull registry.gitlab.com/gdong/dlmonkey
    - docker run -dp 8080:9876 --name dlmonkey -t registry.gitlab.com/gdong/dlmonkey
  environment:
    name: staging
    url: http://localhost:9876
  only:
    - master
  tags:
    - staging

deploy_prod:
  stage: deploy
  script:
    - echo "Deploying to production server"
  environment:
    name: prod
    url: http://www.dlmonkey.com
  when: manual
  only:
    - master

